# Generated by Django 5.2.7 on 2025-10-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
            ],
        ),
    ]
