# Generated by Django 5.2.7 on 2025-11-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="id",
        ),
        migrations.AddField(
            model_name="post",
            name="sno",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
