# Generated by Django 5.2.7 on 2025-11-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment_delete_blogcomments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
