# Generated by Django 5.2.7 on 2025-11-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="id",
        ),
        migrations.AddField(
            model_name="comment",
            name="roll",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
